<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Package Test Suite" tests="12" assertions="8" errors="3" failures="3" skipped="2" time="0.041739">
    <testsuite name="Tests\AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" tests="8" assertions="4" errors="2" failures="2" skipped="2" time="0.011923">
      <testcase name="test_passed" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="9" assertions="1" time="0.007537"/>
      <testcase name="test_error" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="14" assertions="1" time="0.001508">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AssertionsTest::test_error
Failed asserting that false is true.

C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php:16
</failure>
      </testcase>
      <testcase name="test_assertion_isnt_same" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="19" assertions="1" time="0.001332">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\AssertionsTest::test_assertion_isnt_same
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
 Array &amp;0 (
-    'a' =&gt; 'b'
-    'c' =&gt; 'd'
+    'e' =&gt; 'f'
+    0 =&gt; 'g'
+    1 =&gt; 'h'
 )

C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php:21
</failure>
      </testcase>
      <testcase name="test_risky" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="24" assertions="0" time="0.000079">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
      </testcase>
      <testcase name="it_should_be_annotation_test" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="32" assertions="1" time="0.000063"/>
      <testcase name="test_skipped" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="37" assertions="0" time="0.000664">
        <skipped/>
      </testcase>
      <testcase name="test_incomplete" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="42" assertions="0" time="0.000693">
        <skipped/>
      </testcase>
      <testcase name="test_no_assertion" class="Tests\AssertionsTest" classname="Tests.AssertionsTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\AssertionsTest.php" line="47" assertions="0" time="0.000047">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
      </testcase>
    </testsuite>
    <testsuite name="Tests\CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" tests="4" assertions="4" errors="1" failures="1" skipped="0" time="0.029816">
      <testcase name="test_sum" class="Tests\CalculatorTest" classname="Tests.CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" line="18" assertions="1" time="0.001970"/>
      <testcase name="test_sum_fail" class="Tests\CalculatorTest" classname="Tests.CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" line="25" assertions="1" time="0.000132">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Tests\CalculatorTest::test_sum_fail
Failed asserting that 4 is identical to 3.

C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php:29
</failure>
      </testcase>
      <testcase name="test_sum_item" class="Tests\CalculatorTest" classname="Tests.CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" line="32" assertions="1" time="0.000608"/>
      <testcase name="test_sum_item_method_not_call" class="Tests\CalculatorTest" classname="Tests.CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" line="42" assertions="1" time="0.027106">
        <error type="Mockery\Exception\InvalidCountException">Tests\CalculatorTest::test_sum_item_method_not_call
Mockery\Exception\InvalidCountException: Method test(&lt;Any Arguments&gt;) from Mockery_0_App_Item_App_Item should be called&#13;
 exactly 1 times but called 0 times.

C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery\CountValidator\Exact.php:38
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery\Expectation.php:309
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery\ExpectationDirector.php:119
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery\Container.php:301
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery\Container.php:286
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\vendor\mockery\mockery\library\Mockery.php:165
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php:15
</error>
      </testcase>
      <testcase name="test_throw_exception" class="Tests\CalculatorTest" classname="Tests.CalculatorTest" file="C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php" line="54" assertions="0" time="0.000157">
        <error type="Exception">Tests\CalculatorTest::test_throw_exception
Exception:

C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\src\Calculator.php:21
C:\Users\recca\Desktop\vscode-phpunit\server\tests\fixtures\project\tests\CalculatorTest.php:57
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
